export class Excel {
    dni?:string;
    apellido?:string;
    nombre?:string;
    obraSocial?:string;
    edad?:string;
    altura?:string;
    peso?:string;
    temperatura?:string;
    presion?:string;
    clave1?:string;
    valor1?:string;
    clave2?:string;
    valor2?:string;
    clave3?:string;
    valor3?:string;
    perfil?:string;
  
    constructor(
        dni?:string,
        apellido?:string,
        nombre?:string,
        obraSocial?:string,
        edad?:string,
        altura?:string,
        peso?:string,
        temperatura?:string,
        presion?:string,
        clave1?:string,
        valor1?:string,
        clave2?:string,
        valor2?:string,
        clave3?:string,
        valor3?:string,
        perfil?:string
    ){
        dni=dni;
        apellido=apellido;
        nombre=nombre;
        obraSocial=obraSocial;
        edad=edad;
        altura=altura;
        peso=peso;
        temperatura=temperatura;
        presion=presion;
        clave1=clave1;
        valor1=valor1;
        clave2=clave2;
        valor2=valor2;
        clave3=clave3;
        valor3=valor3;
        perfil=perfil;
    }
}